### ISSUE TITLE
Typo on Lecture-08 slide 5 of 19

### ISSUE THREAD

**Issue by townesm** [slu-soc5650/lecture-08#1]
@chris-prener I think there is a typo on Lecture-08 slide 5 "Download States Data".  Should the comment about resolution read that `resolution` is only needed if `cb = TRUE` as it is on the following slide (i.e., slide 6).  Currently slide 5 says that `resolution` is needed if `cb = FALSE` (see below).

`resolution` is only needed if `cb = FALSE`; the three possible values are
“500k”, “5m”, and “20m”. The “20m” data are the most generalized (least
accurate).

**Comment by chris-prener** [comment]
this is now fixed on the slides that are available in this repo, thanks for opening the issue @tnewtson!
